#include "Utils.hlsl"
#pragma kernel CSMain
#pragma kernel Clear

RWTexture2D<float4> Result;
RWTexture2D<float4> Environment;
int seed;

int size;
uint kind;
uint2 pos;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
  if(distance(id.xy,pos)<size)
        Environment[id.xy]=float4(int2float(kind),0,0,0);
}

[numthreads(8,8,1)]
void Clear(uint3 id : SV_DispatchThreadID)
{
    Result[id.xy]=0;
    Environment[id.xy]=0.5f;
}